odgovori = [ # answers for 8ball in Croatian
    "Zasigurno",
    "Bez sumnje",
    "U to se možeš uzdati",
    "Da, definitivno",
    "Naravno",
    "Da je očit odgovor",
    "Da, najvjerovatnije",
    "Da.",
    "Da, retarde",
    "Svi znakovi upućuju na da",
    "Ne razumijem, pokušaj ponovno",
    "Kakvo je to pitanje jebemti",
    "Pitaj ponovo kasnije",
    "Nemogu sada predvidjeti",
    "Usredotoči se i pitaj ponovno",
    "Ne računaj na to",
    "Izgledi nisu dobri",
    "Moji izvori kažu ne",
    "Sumnjam",
    "Ne, zašto pitaš"
]
answers = [ # answers for 8ball in English
    'It is certain',
    'It is decidedly so',
    'Without a doubt',
    'Yes – definitely',
    'You may rely on it',
    'As I see it, yes',
    'Most likely',
    'Outlook good',
    'Yes Signs point to yes',
    'Well, obviously...',
    'Reply hazy', 'try again',
    'Ask again later',
    'Better not tell you now',
    'Cannot predict now',
    'Concentrate and ask again',
    'Dont count on it',
    'My reply is no',
    'My sources say no',
    'Outlook not so good',
    'Very doubtful'
]
